// import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/commponents/Navbar";
import Footer from "@/commponents/Footer";
import { ThemeProvider } from "@/contexts/ThemeContext";




// export const metadata: Metadata = {
//   title: "Home",
//   description: "Generated by next.js Home",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
      </ThemeProvider>
    </html>
  );
}
